### ISSUE TITLE
dependencies 

### ISSUE THREAD

**Issue by ngobibibnbe** [zpzim/LAMP-ICDM2019#1]
Please which dependencies did you used for the implementation?

**Comment by zpzim** [comment]
Hey sorry I didn't see this. Everything should be included in the imported dependencies in the python files.

If you want to know the exact version of each dependency, unfortunately I don't think I have this information.

main deps are keras, numpy, scipy, pandas, tensorflow.

**Comment by ngobibibnbe** [comment]
Please mention the version of tensor flow and keras. It's really difficult
to find them

**Comment by zpzim** [comment]
I have updated the repo to be compatible with tf2 and removed deprecated usage of old apis. I also added a requirements.txt which should be enough to run the code given gpu support is correctly enabled on the system via cuda/cudnn/etc.

Please let me know if you have any issues running or understanding the code. Sorry for the delay on this.

**Comment by ngobibibnbe** [comment]
Thank you Zack 😊
